apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openobserve-collector
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/smoothzz/argocd-repo
      targetRevision: main
      path: openobserve-collector
    - repoURL: https://charts.openobserve.ai/
      chart: openobserve-collector
      targetRevision: 0.4.6
      helm:
        releaseName: openobserve-collector
        values: |
          k8sCluster: "smoothz"
          gateway:
            enabled: false
          opentelemetry-operator:
            enabled: false
          exporters:
            otlphttp/openobserve:
              endpoint: http://openobserve-openobserve-standalone.openobserve:5080/api/default/
            otlphttp/openobserve_k8s_events:
              endpoint: http://openobserve-openobserve-standalone.openobserve:5080/api/default/
              headers:
                stream-name: k8s_events
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openobserve-collector
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true