resources:
- cilium/app.yaml
- kyverno/app.yaml
- kyverno-policies/app.yaml
- longhorn/app.yaml
- minio/app.yaml
- velero/app.yaml
- openobserve/app.yaml
- openobserve-collector/app.yaml
- opentelemetry-operator/app.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization