apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxdemo
  name: nginxdemo
  namespace: default
  resourceVersion: "1740"
spec:
  clusterIP: 10.43.129.162
  clusterIPs:
  - 10.43.129.162
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30003
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxdemo
  sessionAffinity: None
  type: NodePort
