apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/smoothzz/argocd-repo
      targetRevision: main
      path: sealed-secrets/crds
    - repoURL: https://bitnami.github.io/sealed-secrets/
      chart: sealed-secrets
      targetRevision: 2.19.3
      helm:
        releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true