apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  source:
    chart: portainer
    repoURL: https://portainer.github.io/k8s/
    targetRevision: 1.16.1
    helm:
      releaseName: portainer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: portainer