apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts/
    targetRevision: 12.1.0
    helm:
      releaseName: velero
      values: |
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.14.2
            volumeMounts:
              - mountPath: /target
                name: plugins
        deployNodeAgent: true
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero
              config:
                region: us-east-1
                s3Url: http://minio.minio:9000
                s3ForcePathStyle: "true"
                insecureSkipTLSVerify: "true"
        credentials:
          useSecret: true
          secretContents:
            cloud: |
              [default]
              aws_access_key_id = minioadmin
              aws_secret_access_key = minioadmin
        snapshotsEnabled: false
        backupsEnabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: velero
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true